name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-static-app:latest

  trigger-jenkins:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # Trigger Jenkins job
      - name: Trigger Jenkins Job
        run: |
          curl -X POST "http://${{ secrets.JENKINS_SERVER_IP }}:8080/job/your-jenkins-job-name/build?token=${{ secrets.JENKINS_TOKEN }}"
